name = "scrollcorner-site"
workers_dev = false

[assets]
directory = "out"
not_found_handling = "404-page"

routes = [
  { pattern = "scrollcorner.com", custom_domain = true },
  { pattern = "www.scrollcorner.com", custom_domain = true },
]
