name = "scrollcorner-site"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

routes = [
  { pattern = "scrollcorner.com", custom_domain = true },
  { pattern = "www.scrollcorner.com", custom_domain = true },
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
